### PR TITLE
Port folio page styling

### PR DESCRIPTION
**Pull request by rachithans**
-Made Table headers sticky
-Added Table header for watchlist

### CODE REVIEW

**Review by Gufran-ahmed — CHANGES_REQUESTED** [review]
I wouldn't make the header on holdings and other smaller headers sticky since it is obstructing/covering other table below it. 
I am not sure if its only my local  computer but the blue header on dashboard page is not aligned to the table in my local on the contrary the watchlist header is aligned and is responsive so that's good.

**Comment by rachithans** [comment]
I have removed sticky headers from the portfolio page and for the dashboard table header, Edward is working on that.

**Comment by Costermonger** [comment]
> I wouldn't make the header on holdings and other smaller headers sticky since it is obstructing/covering other table below it.
> I am not sure if its only my local computer but the blue header on dashboard page is not aligned to the table in my local on the contrary the watchlist header is aligned and is responsive so that's good.

Do you want it to be the same width as the table items? For the dashboard header.

**Comment by Gufran-ahmed** [comment]
> > I wouldn't make the header on holdings and other smaller headers sticky since it is obstructing/covering other table below it.
> > I am not sure if its only my local computer but the blue header on dashboard page is not aligned to the table in my local on the contrary the watchlist header is aligned and is responsive so that's good.
> 
> Do you want it to be the same width as the table items? For the dashboard header.

**Comment by Gufran-ahmed** [comment]
> > I wouldn't make the header on holdings and other smaller headers sticky since it is obstructing/covering other table below it.
> > I am not sure if its only my local computer but the blue header on dashboard page is not aligned to the table in my local on the contrary the watchlist header is aligned and is responsive so that's good.
> 
> Do you want it to be the same width as the table items? For the dashboard header.

Yeah wouldn't that make it look more neat

**Comment by joel-richards** [comment]
I'm doing the styling. I'll have it fixed in a few on a new branch

**Pull request closed without merging**
